---
- hosts: octave-hed
  vars:
    octave_url: https://ftp.gnu.org/gnu/octave/octave-4.2.1.tar.xz
  remote_user: vagrant
  become: yes

  tasks:
  - name: install build-requirement for octave
    apt:
      pkg: octave
      state: build-dep

  - name: extract tarball
    unarchive:
      src: octave-4.2.1.tar.xz
      dest: /tmp
      
  - name: configure octave
    command: chdir=/tmp/octave-4.2.1 ./configure --prefix=/opt/octave

  - name: make octave
    command: chdir=/tmp/octave-4.2.1 make all

  - name: install octave
    command: chdir=/tmp/octave-4.2.1 make install
